# Generated by Django 5.2.6 on 2025-09-15 11:18

import fernet_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.CharField(
                        default="kbZWSEqWuQYTHV3E", max_length=32, unique=True
                    ),
                ),
                ("name", fernet_fields.fields.EncryptedCharField(max_length=200)),
                (
                    "notes",
                    fernet_fields.fields.EncryptedTextField(blank=True, null=True),
                ),
                (
                    "name_hash",
                    models.CharField(db_index=True, editable=False, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
